/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface PaymentType { 'id' : bigint, 'name' : string }
export interface Product {
  'id' : bigint,
  'name' : string,
  'stock' : bigint,
  'barcode' : string,
  'price' : bigint,
}
export interface Sale {
  'id' : bigint,
  'date' : Time,
  'paymentTypeId' : bigint,
  'totalAmount' : bigint,
  'customerId' : bigint,
  'items' : Array<SaleItem>,
}
export interface SaleItem {
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'createCustomer' : ActorMethod<[string, string, string], bigint>,
  'createPaymentType' : ActorMethod<[string], bigint>,
  'createProduct' : ActorMethod<[string, bigint, string, bigint], bigint>,
  'createSale' : ActorMethod<[bigint, bigint, Array<SaleItem>], bigint>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deletePaymentType' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteSale' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllPaymentTypes' : ActorMethod<[], Array<PaymentType>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getPaymentType' : ActorMethod<[bigint], PaymentType>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getSale' : ActorMethod<[bigint], Sale>,
  'seed' : ActorMethod<[], undefined>,
  'updateCustomer' : ActorMethod<[bigint, string, string, string], undefined>,
  'updatePaymentType' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];