/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SaleItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentType = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'paymentTypeId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(SaleItem),
});

export const idlService = IDL.Service({
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createPaymentType' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createSale' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(SaleItem)], [IDL.Nat], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deletePaymentType' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteSale' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllPaymentTypes' : IDL.Func([], [IDL.Vec(PaymentType)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getPaymentType' : IDL.Func([IDL.Nat], [PaymentType], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getSale' : IDL.Func([IDL.Nat], [Sale], ['query']),
  'seed' : IDL.Func([], [], []),
  'updateCustomer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePaymentType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SaleItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentType = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'paymentTypeId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(SaleItem),
  });
  
  return IDL.Service({
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createPaymentType' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createSale' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(SaleItem)],
        [IDL.Nat],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deletePaymentType' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteSale' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllPaymentTypes' : IDL.Func([], [IDL.Vec(PaymentType)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getPaymentType' : IDL.Func([IDL.Nat], [PaymentType], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getSale' : IDL.Func([IDL.Nat], [Sale], ['query']),
    'seed' : IDL.Func([], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePaymentType' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };